type AutoGenerated struct {
	Booleanfield bool `json:"booleanfield"`
	Inconsistentarray []Inconsistentarray `json:"inconsistentarray,omitempty"`
	Date string `json:"date,omitempty"`
}
type Features struct {
	Age int `json:"age,omitempty"`
	Height int `json:"height,omitempty"`
	Gender string `json:"gender,omitempty"`
}
type Inconsistentarray struct {
	ID int `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
	Features Features `json:"features,omitempty"`
}
